import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { SeriesModel } from "@/models/Series";
import { ProductModel } from "@/models/Product";

const series = [
  { title:"Shadows of the Forgotten",description:"A detective discovers her missing sister left behind cryptic audio messages leading to a secret society.",coverImage:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600",genre:"Thriller",language:"English",narrator:"Aria Voss",rating:4.8,isFeatured:true,isTrending:true,totalPlays:128450,tags:["thriller","mystery","dark"],
    episodes:[
      {title:"The Last Message",description:"Maya receives a voicemail from her sister — three years after her disappearance.",duration:1842,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",episodeNumber:1,isLocked:false,playCount:45200,transcript:"The city never sleeps. That's what they say about Noirdale. And I've spent fifteen years proving them right, chasing ghosts through rain-slicked alleys and fluorescent-lit interrogation rooms. My name is Maya Reyes. I'm a detective. And three years ago, my sister Sarah vanished without a trace.\n\nI had given up hope. Truly. Until last Tuesday night when my phone rang at 2:47 AM and her voice came through the static like something dredged from deep water:\n\n'Maya. Don't trust the Archive. They're watching. I left something for you — under the oak at Morrow Park. Come alone. Please.'\n\nThat was it. Static. Silence."},
      {title:"The Archive",description:"Maya finds a hidden dossier linking her sister to The Archive.",duration:2156,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",episodeNumber:2,isLocked:false,playCount:38700,transcript:"The oak at Morrow Park is three hundred years old. Inside: a USB drive, a photograph, and a single page of handwritten notes. The photograph stopped my breath. Sarah. My sister. Standing beside a man I didn't recognize in front of a building I'd never seen. She looked purposeful. Like she knew exactly what she was doing."},
      {title:"Static",description:"A glitch in the recordings reveals someone listening in real time.",duration:1930,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",episodeNumber:3,isLocked:false,playCount:29100,transcript:""},
      {title:"The Informant",description:"A mysterious caller offers to help Maya — but their price is steep.",duration:2280,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",episodeNumber:4,isLocked:true,playCount:18900,transcript:""},
      {title:"Underground",description:"Following coordinates, Maya descends into tunnels beneath the city.",duration:2410,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",episodeNumber:5,isLocked:true,playCount:12300,transcript:""},
    ]},
  { title:"The Silk Road Chronicles",description:"A young merchant navigates treachery and romance on the ancient trading routes searching for a legendary artifact.",coverImage:"https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600",genre:"Historical Adventure",language:"English",narrator:"Omar Khalil",rating:4.7,isFeatured:true,isTrending:false,totalPlays:89200,tags:["historical","adventure","silk road"],
    episodes:[
      {title:"Departure from Chang'an",description:"Young merchant Kiran leaves the imperial capital with a caravan bound west.",duration:2100,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",episodeNumber:1,isLocked:false,playCount:31000,transcript:"Chang'an in the year 742 AD smells of cinnamon, horse dung, woodsmoke, and ambition. The morning I left, the eastern gate was jammed with three hundred camels, their bells creating a dissonant music that would follow me in dreams for years."},
      {title:"The Dunhuang Caves",description:"Kiran discovers a secret hidden for centuries within the painted caves.",duration:2340,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",episodeNumber:2,isLocked:false,playCount:22000,transcript:""},
      {title:"Desert of Whispers",description:"Crossing the Taklamakan, the caravan encounters dangerous rivals.",duration:2560,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",episodeNumber:3,isLocked:false,playCount:17500,transcript:""},
      {title:"The Blue Merchant",description:"In Samarkand, the legendary merchant holds more secrets than expected.",duration:2700,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",episodeNumber:4,isLocked:true,playCount:9800,transcript:""},
    ]},
  { title:"The Quantum Diaries",description:"A physicist begins receiving messages from parallel versions of herself, each warning about a different imminent catastrophe.",coverImage:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600",genre:"Sci-Fi",language:"English",narrator:"Dr. Elena Cross",rating:4.9,isFeatured:true,isTrending:true,totalPlays:156700,tags:["sci-fi","quantum","thriller"],
    episodes:[
      {title:"Signal from Tomorrow",description:"Dr. Nadia receives a mathematical proof in her own handwriting — sent from the future.",duration:2200,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",episodeNumber:1,isLocked:false,playCount:52400,transcript:"The message arrived the way fundamental things always do: quietly, without fanfare, embedded in the noise. I was running a standard quantum error correction protocol at 11 PM when the analyzer flagged an anomaly."},
      {title:"Branching Point",description:"A second message arrives from a different version of Nadia — with opposite instructions.",duration:2440,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",episodeNumber:2,isLocked:false,playCount:41200,transcript:""},
      {title:"The Multiverse Caucus",description:"Nadia discovers she is not the only physicist receiving cross-timeline messages.",duration:2650,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",episodeNumber:3,isLocked:false,playCount:33800,transcript:""},
      {title:"Collapse Function",description:"The messages stop. Something has gone wrong in the future.",duration:2900,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",episodeNumber:4,isLocked:true,playCount:21100,transcript:""},
      {title:"Entanglement",description:"The final choice that defines all timelines.",duration:3100,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",episodeNumber:5,isLocked:true,playCount:14700,transcript:""},
    ]},
  { title:"Mumbai Monsoon",description:"A romantic drama following two strangers whose lives keep intersecting through a local radio station across three monsoon seasons.",coverImage:"https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600",genre:"Romance Drama",language:"English",narrator:"Priya Mehta",rating:4.6,isFeatured:false,isTrending:true,totalPlays:74600,tags:["romance","drama","India","monsoon"],
    episodes:[
      {title:"First Rain",description:"Zara and Arjun take shelter in the same tea stall and discover they host competing radio shows.",duration:1920,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",episodeNumber:1,isLocked:false,playCount:28300,transcript:"June 7th. The first rain of the season came the way it always does in Mumbai — not gradually but all at once. I was outside on Linking Road, headphones around my neck, late for a meeting I didn't want to attend, when the sky opened."},
      {title:"Static Between Stations",description:"Zara and Arjun start a secret correspondence through song dedications.",duration:2050,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",episodeNumber:2,isLocked:false,playCount:21100,transcript:""},
      {title:"The Second Season",description:"A year passes. Arjun has left for Delhi. Then the rains return.",duration:2180,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",episodeNumber:3,isLocked:true,playCount:14200,transcript:""},
    ]},
  { title:"Folktales from the Himalayas",description:"Ancient stories from Himalayan villages narrated in the tradition of firelight storytelling.",coverImage:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600",genre:"Folklore",language:"English",narrator:"Tenzin Norbu",rating:4.5,isFeatured:false,isTrending:false,totalPlays:43200,tags:["folklore","himalayan","spiritual"],
    episodes:[
      {title:"The Snow Leopard's Gift",description:"A shepherd who rescues an injured snow leopard receives a gift that changes his perception of the mountain.",duration:1650,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",episodeNumber:1,isLocked:false,playCount:14500,transcript:"In the old stories, the snow leopard is called the Ghost of the Mountain. It walks the high passes where the air is thin and the gods are close. Karma saw one in his fourteenth year."},
      {title:"The River That Remembers",description:"A village elder tells of a river that holds the memories of all who have crossed it.",duration:1780,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",episodeNumber:2,isLocked:false,playCount:10200,transcript:""},
      {title:"The Weaver of Clouds",description:"High above the treeline lives a woman who weaves the clouds each morning.",duration:1540,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",episodeNumber:3,isLocked:true,playCount:8100,transcript:""},
    ]},
  { title:"Dark Web",description:"A journalist investigating online extremism starts receiving messages from an anonymous source who seems to know her next discovery before she makes it.",coverImage:"https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600",genre:"Cyber Thriller",language:"English",narrator:"Sam Rivers",rating:4.4,isFeatured:false,isTrending:true,totalPlays:67800,tags:["cyber","thriller","journalism"],
    episodes:[
      {title:"The Source",description:"Journalist Jo Park receives an encrypted message that dismantles her entire current story.",duration:2030,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",episodeNumber:1,isLocked:false,playCount:24600,transcript:"I have been a journalist for eleven years. I have had good sources and bad sources. I was not careful enough for this one."},
      {title:"Mirror Sites",description:"Jo discovers the Forum has been feeding false information to multiple journalists simultaneously.",duration:2180,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",episodeNumber:2,isLocked:false,playCount:19300,transcript:""},
      {title:"The Real Network",description:"The anonymous source reveals they are a former insider — and the Forum's goal is far more dangerous than suspected.",duration:2360,audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",episodeNumber:3,isLocked:true,playCount:13200,transcript:""},
    ]},
];

const products = [
  {name:"Naad Wireless Earbuds Pro",description:"Premium audiophile-grade wireless earbuds with 40hr battery, ANC, and custom voice-tuning profile.",price:4999,images:["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600"],category:"accessories",tags:["earbuds","wireless","premium"],stock:150,rating:4.8,reviews:234},
  {name:"Story Notebook — Leather Bound",description:"Handmade full-grain leather journal with 200 pages of archival paper and ribbon bookmark.",price:899,images:["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600"],category:"accessories",tags:["notebook","leather"],stock:80,rating:4.6,reviews:89},
  {name:"Himalayan Crystal Bookmark Set",description:"Set of 3 hand-cut crystal bookmarks with brass fittings, inscribed with quotes from Folktales.",price:349,images:["https://images.unsplash.com/photo-1481237560839-5a9e7c7ff00e?w=600"],category:"accessories",relatedSeries:"Folktales from the Himalayas",tags:["bookmark","crystal","gift"],stock:200,rating:4.4,reviews:56},
  {name:"Naad Podcast Mic Stand — Walnut",description:"Desktop microphone stand crafted from solid walnut with adjustable height and minimal aesthetic.",price:2199,images:["https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=600"],category:"accessories",tags:["mic","stand","creator"],stock:45,rating:4.7,reviews:78},
  {name:"The Listener Oversized Tee — Midnight",description:"Premium 320gsm cotton oversized tee with minimal embroidered waveform motif. Sizes XS–3XL.",price:799,images:["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600"],category:"clothing",tags:["tshirt","cotton","minimal"],stock:300,rating:4.5,reviews:145},
  {name:"Silk Road Scarf — Hand Block Printed",description:"100% silk scarf hand block-printed in Jaipur with a pattern inspired by ancient trade routes.",price:1499,images:["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600"],category:"clothing",relatedSeries:"The Silk Road Chronicles",tags:["scarf","silk","handmade"],stock:60,rating:4.9,reviews:42},
  {name:"Monsoon Linen Kurta — Unisex",description:"Breezy handloom linen kurta with subtle rain-drop embroidery along the yoke and cuffs.",price:1899,images:["https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600"],category:"clothing",relatedSeries:"Mumbai Monsoon",tags:["kurta","linen","sustainable"],stock:120,rating:4.6,reviews:67},
  {name:"Dark Web Hoodie — Charcoal",description:"Heavyweight 420gsm French terry hoodie with glitch-text back print. Drop-shoulder fit.",price:2499,images:["https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600"],category:"clothing",relatedSeries:"Dark Web",tags:["hoodie","streetwear","heavy"],stock:90,rating:4.7,reviews:98},
  {name:"Himalayan Singing Bowl — Large",description:"Hand-hammered bronze singing bowl from Kathmandu, 22cm diameter. Comes with striker and cushion.",price:2799,images:["https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?w=600"],category:"handicrafts",relatedSeries:"Folktales from the Himalayas",tags:["bowl","himalayan","meditation"],stock:30,rating:4.9,reviews:112},
  {name:"Caravanserai Miniature — Terracotta",description:"Hand-painted terracotta miniature depicting a Silk Road caravanserai at dusk. Each unique.",price:1299,images:["https://images.unsplash.com/photo-1515023115689-589c33041d3c?w=600"],category:"handicrafts",relatedSeries:"The Silk Road Chronicles",tags:["miniature","terracotta","collectible"],stock:25,rating:4.8,reviews:34},
  {name:"Woven Wall Tapestry — Mountain Spirit",description:"Hand-loomed wool tapestry in natural dyes depicting a snow leopard. 60cm × 90cm.",price:3499,images:["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"],category:"handicrafts",tags:["tapestry","wool","wall art"],stock:15,rating:4.9,reviews:28},
  {name:"Naad Premium Tote — Natural Canvas",description:"Heavy-duty 16oz canvas tote with leather handles, screenprinted with the Naad waveform logo.",price:599,images:["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600"],category:"merchandise",tags:["tote","canvas","eco"],stock:400,rating:4.4,reviews:189},
  {name:"Enamel Pin Set — Series Characters",description:"Set of 6 illustrated enamel pins featuring characters from Naad's most popular series.",price:449,images:["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"],category:"merchandise",tags:["pins","enamel","collectible"],stock:500,rating:4.6,reviews:234},
  {name:"The Quantum Diaries — Collector's Box",description:"Deluxe collector's edition with printed transcript book, props, and a limited print.",price:2999,images:["https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600"],category:"merchandise",relatedSeries:"The Quantum Diaries",tags:["collectible","box set","limited"],stock:100,rating:4.9,reviews:67},
];

export async function POST() {
  try {
    await connectDB();
    await SeriesModel.deleteMany({});
    await ProductModel.deleteMany({});
    const s = await SeriesModel.insertMany(series.map(x=>({...x,totalEpisodes:x.episodes.length})));
    const p = await ProductModel.insertMany(products);
    return NextResponse.json({ ok: true, series: s.length, products: p.length });
  } catch (e) { return NextResponse.json({ error: String(e) }, { status: 500 }); }
}
