export const sampleSeries = [
  {
    title: "Shadows of the Forgotten",
    description: "A gripping psychological thriller about a detective who discovers her missing sister left behind a trail of cryptic audio messages. Each episode unravels a darker layer of a secret society operating in the city's underbelly.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600",
    genre: "Thriller",
    language: "English",
    narrator: "Aria Voss",
    rating: 4.8,
    isFeatured: true,
    isTrending: true,
    totalPlays: 128450,
    tags: ["thriller", "mystery", "dark", "detective"],
    episodes: [
      { title: "The Last Message", description: "Detective Maya receives a voicemail from her sister — three years after her disappearance.", duration: 1842, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", episodeNumber: 1, isLocked: false, playCount: 45200, transcript: "The city never sleeps. That's what they say about Noirdale. And I've spent fifteen years proving them right, chasing ghosts through rain-slicked alleys and fluorescent-lit interrogation rooms. My name is Maya Reyes. I'm a detective. And three years ago, my sister Sarah vanished without a trace.\n\nI had given up hope. Truly. Until last Tuesday night when my phone rang at 2:47 AM and her voice came through the static like something dredged from deep water:\n\n'Maya. Don't trust the Archive. They're watching. I left something for you — under the oak at Morrow Park. Come alone. Please.'\n\nThat was it. Static. Silence.\n\nI sat in my apartment for a long time, the recording playing over and over, her voice growing more familiar with each pass. Three years of silence and now this. My hands were steady — I'm a detective, steadiness is a professional requirement — but my chest felt like it had caved in.\n\nI drove to Morrow Park before dawn." },
      { title: "The Archive", description: "Maya finds a hidden dossier that links her sister to a shadowy organization known only as The Archive.", duration: 2156, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", episodeNumber: 2, isLocked: false, playCount: 38700, transcript: "The oak at Morrow Park is three hundred years old. The city grew up around it like scar tissue around a wound. At 4 AM, in the flat grey light before sunrise, it looked like a giant's skeleton.\n\nThe package was buried shallow — a waterproof case, military-grade, the kind you could find at any army surplus store. Inside: a USB drive, a photograph, and a single page of handwritten notes.\n\nThe photograph stopped my breath.\n\nSarah. My sister. Standing beside a man I didn't recognize in front of a building I'd never seen. She looked — not afraid. Something else. Purposeful. Like she knew exactly what she was doing and had made peace with it.\n\nThe handwritten page said only: 'The Archive collects things that should not exist. Recordings. Confessions. Proof. They have been doing it for forty years. I found three of the recordings. That's why I ran.'" },
      { title: "Static", description: "A glitch in the recordings reveals a voice that shouldn't be there — someone listening in real time.", duration: 1930, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", episodeNumber: 3, isLocked: false, playCount: 29100, transcript: "I played the USB recordings in my car with the engine off and the doors locked.\n\nThere were eleven files. The first ten were what Sarah described — confessions, financial records, blackmail material on judges, councilmembers, a federal prosecutor. Career-ending things. Life-ending things. The Archive had been collecting these for decades, using them as leverage, building a silent empire of favors owed.\n\nThe eleventh file was different.\n\nIt was a recording of me. From three days ago. In my apartment.\n\nI heard myself making coffee. I heard myself talking to my cat. I heard myself crying — just for a moment, just briefly, something I do sometimes at night when the precinct is quiet in my memory and my sister's absence becomes a physical ache.\n\nSomebody had been in my apartment. Or they had gotten to my devices. Either way: they knew I had the package. They were already watching." },
      { title: "The Informant", description: "A mysterious caller offers to help Maya — but their price is steep.", duration: 2280, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", episodeNumber: 4, isLocked: true, playCount: 18900, transcript: "" },
      { title: "Underground", description: "Following coordinates from the dossier, Maya descends into a network of tunnels beneath the city.", duration: 2410, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", episodeNumber: 5, isLocked: true, playCount: 12300, transcript: "" },
    ]
  },
  {
    title: "The Silk Road Chronicles",
    description: "An epic journey through ancient trading routes as a young merchant navigates treachery, romance, and the search for a legendary artifact. Told through vivid sensory storytelling and immersive sound design.",
    coverImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600",
    genre: "Historical Adventure",
    language: "English",
    narrator: "Omar Khalil",
    rating: 4.7,
    isFeatured: true,
    isTrending: false,
    totalPlays: 89200,
    tags: ["historical", "adventure", "silk road", "epic"],
    episodes: [
      { title: "Departure from Chang'an", description: "Young merchant Kiran leaves the imperial capital with a caravan bound for the western lands.", duration: 2100, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", episodeNumber: 1, isLocked: false, playCount: 31000, transcript: "Chang'an in the year 742 AD smells of cinnamon, horse dung, woodsmoke, and ambition. The morning I left, the eastern gate was jammed with three hundred camels, their bells creating a dissonant music that would follow me in dreams for years.\n\nMy father had given me a simple instruction: go west. Find the blue merchant. Return with what he carries.\n\nHe would not tell me what the merchant carried. He would not tell me how to find him. 'The road will tell you,' he said, which is the kind of advice fathers give when they have no better answer.\n\nI was nineteen years old. My name is Kiran Singh. My father was a middling trader of spices and lacquerware. What I carried in my saddlebags was a letter of introduction, forty gold coins, and absolutely no idea what I was doing.\n\nThe caravan master was a Sogdian named Rustam who had made the crossing eleven times. He looked at my soft hands and clean clothes and said, in accented Mandarin, 'You will either die or become interesting. Let us find out which.'" },
      { title: "The Dunhuang Caves", description: "The caravan rests at Dunhuang, where Kiran discovers a secret hidden for centuries within the painted caves.", duration: 2340, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", episodeNumber: 2, isLocked: false, playCount: 22000, transcript: "The Mogao Caves had been carved into the cliff face over three centuries by devoted hands. Five hundred caves, some no bigger than a closet, others vast cathedral spaces where the painted Buddhas watched you with eyes that had seen empires rise and fall.\n\nI hired a local guide named Mei, who had the efficient manner of someone who has answered the same questions ten thousand times. She was unimpressed by everything including, apparently, me.\n\n'Most merchants look at the paintings and see decoration,' she said. 'A few look and see messages.'\n\n'Messages from whom?' I asked.\n\nShe looked at me for a long moment. Then she said, 'Come back at midnight. Bring the letter your father gave you.'\n\nI don't know how she knew about the letter. I hadn't mentioned it. When I returned at midnight with a lamp and a racing heart, Cave 17 — the Library Cave, sealed for seven hundred years before its accidental rediscovery — was standing open." },
      { title: "Desert of Whispers", description: "Crossing the Taklamakan, Kiran's caravan encounters a rival group with dangerous intentions.", duration: 2560, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", episodeNumber: 3, isLocked: false, playCount: 17500, transcript: "" },
      { title: "The Blue Merchant", description: "After months of travel, Kiran finally reaches Samarkand — and the legendary merchant holds more secrets than expected.", duration: 2700, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", episodeNumber: 4, isLocked: true, playCount: 9800, transcript: "" },
    ]
  },
  {
    title: "Mumbai Monsoon",
    description: "A romantic drama set across three monsoon seasons in Mumbai, following two strangers whose lives keep intersecting through a local radio station, street food stalls, and the city's relentless heartbeat.",
    coverImage: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600",
    genre: "Romance Drama",
    language: "English",
    narrator: "Priya Mehta",
    rating: 4.6,
    isFeatured: false,
    isTrending: true,
    totalPlays: 74600,
    tags: ["romance", "drama", "India", "monsoon", "urban"],
    episodes: [
      { title: "First Rain", description: "When the first monsoon rains hit Mumbai, Zara and Arjun take shelter in the same tiny tea stall and discover they both host competing radio shows.", duration: 1920, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", episodeNumber: 1, isLocked: false, playCount: 28300, transcript: "June 7th. The first rain of the season came the way it always does in Mumbai — not gradually but all at once, like the sky making a decision. One moment: sunshine, heat, the thick smell of pre-monsoon dust. The next: a wall of water descending from Dharavi to Colaba simultaneously.\n\nI was outside the tea stall on linking Road, headphones around my neck, late for a meeting I didn't want to attend, when the sky opened. I ducked inside. The stall was the size of a generous closet: three stools, one counter, a proprietor named Suresh who had been making the same chai for thirty-two years.\n\nThere was already someone on the third stool.\n\nHe had the look of someone who had also ducked in from the rain — damp shoulders, surprised expression. He was holding a notebook dense with handwriting. He looked up when I sat down and said, 'You're the voice from Raag FM. Seven to nine PM.'\n\n'And you're the other one,' I said. 'The rival.' He did a late-night jazz show that occupied the frequency just above mine. I had never liked it. I had also listened to every episode.\n\n'Arjun,' he said, and held out his hand.\n\n'Zara,' I said. Outside, Mumbai was drowning beautifully." },
      { title: "Static Between Stations", description: "Zara and Arjun start a secret correspondence through songs they dedicate to each other on their respective shows.", duration: 2050, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3", episodeNumber: 2, isLocked: false, playCount: 21100, transcript: "" },
      { title: "The Second Season", description: "A year passes. Arjun has left for Delhi. Zara has changed her show format. Then the rains return.", duration: 2180, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3", episodeNumber: 3, isLocked: true, playCount: 14200, transcript: "" },
      { title: "Frequency", description: "A late night broadcast, a dedicated song, and a city that seems to conspire toward reunion.", duration: 2350, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", episodeNumber: 4, isLocked: true, playCount: 8900, transcript: "" },
    ]
  },
  {
    title: "The Quantum Diaries",
    description: "A mind-bending science fiction thriller where a physicist begins receiving messages from parallel versions of herself, each warning about a catastrophic event that is different in every reality — but always imminent.",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600",
    genre: "Sci-Fi",
    language: "English",
    narrator: "Dr. Elena Cross",
    rating: 4.9,
    isFeatured: true,
    isTrending: true,
    totalPlays: 156700,
    tags: ["sci-fi", "quantum", "thriller", "parallel worlds"],
    episodes: [
      { title: "Signal from Tomorrow", description: "Dr. Nadia receives a mathematical proof in her own handwriting — sent from three years in the future.", duration: 2200, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", episodeNumber: 1, isLocked: false, playCount: 52400, transcript: "The message arrived the way fundamental things always do: quietly, without fanfare, embedded in the noise.\n\nI was running a standard quantum error correction protocol at 11 PM on a Thursday when the analyzer flagged an anomaly. Not a technical error. The system was working perfectly. The anomaly was in what it was receiving.\n\nA message. Structured. Mathematical. In a cipher I recognized because I had invented it — three years ago, for a paper that hadn't been published yet. A paper I hadn't told anyone about.\n\nThe message, decoded, was a proof. A proof of something I had been trying to solve for two years, a problem in quantum gravity that my advisor had called 'probably unsolvable in our lifetimes.' The proof was elegant. It was correct. I checked it four times.\n\nAt the bottom of the proof, in notation I use only in my private journals:\n\n'Nadia — don't go to Geneva. Tell no one about this yet. Everything depends on the next six weeks. — N.'\n\nSigned with my own name. The same handwriting as the proof. The same handwriting as mine." },
      { title: "Branching Point", description: "A second message arrives, from a different version of Nadia — and the two futures are catastrophically different.", duration: 2440, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", episodeNumber: 2, isLocked: false, playCount: 41200, transcript: "The second message came six days later, same channel, same anomaly signature. But this time the cipher was slightly different — a variation of my code I had considered but discarded. As if another version of me had made different choices.\n\nThis message was shorter:\n\n'Go to Geneva. The proof is wrong. Going wrong is necessary. Don't trust the first message. — N.'\n\nTwo messages. Two versions of me. Diametrically opposite instructions. One of them was lying, or mistaken, or had been compromised. Or perhaps, in their respective branching timelines, both were completely right.\n\nI spent 72 hours at my whiteboard. At the end, I had something that scared me more than either message: a proof that both could be true simultaneously. That the divergence point — the moment where the timelines split — was a choice I hadn't made yet. A choice about which message to believe.\n\nThe act of choosing was itself the branch point.\n\nWhichever way I chose, I would become the version who sent that message back." },
      { title: "The Multiverse Caucus", description: "Nadia discovers she is not the only physicist receiving messages across timelines.", duration: 2650, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", episodeNumber: 3, isLocked: false, playCount: 33800, transcript: "" },
      { title: "Collapse Function", description: "The messages stop. Something has gone wrong in the future — or everything has gone right.", duration: 2900, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", episodeNumber: 4, isLocked: true, playCount: 21100, transcript: "" },
      { title: "Entanglement", description: "The final episode. Nadia must make the choice that defines all timelines — and learn what she has already sacrificed.", duration: 3100, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", episodeNumber: 5, isLocked: true, playCount: 14700, transcript: "" },
    ]
  },
  {
    title: "Folktales from the Himalayas",
    description: "A collection of ancient stories from Himalayan villages, narrated in the tradition of firelight storytelling. Each episode presents a complete tale exploring wisdom, nature, spirits, and the human heart.",
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600",
    genre: "Folklore",
    language: "English",
    narrator: "Tenzin Norbu",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    totalPlays: 43200,
    tags: ["folklore", "himalayan", "spiritual", "traditional", "wisdom"],
    episodes: [
      { title: "The Snow Leopard's Gift", description: "A lonely shepherd who rescues an injured snow leopard receives a gift that changes his perception of the mountain forever.", duration: 1650, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", episodeNumber: 1, isLocked: false, playCount: 14500, transcript: "In the old stories, the snow leopard is called the Ghost of the Mountain. It walks the high passes where the air is thin and the gods are close, and most people go their whole lives without seeing one.\n\nKarma saw one in his fourteenth year.\n\nHe was returning late from the high pasture — later than he should have been, later than his father would forgive without words — when he heard something in the boulder field below the glacier. Not a usual sound. A sound like patience in pain, if patience made a sound.\n\nThe leopard was trapped. A hind leg caught between two boulders that had shifted with the freeze. She was the most beautiful thing Karma had ever seen: pale as new snow, spotted like night sky, eyes the color of pale winter sky.\n\nShe watched him approach without flinching. This is the part of the story that people always ask about. Shouldn't she have been afraid? Shouldn't she have fought?\n\nKarma says: she knew. She had been waiting for him specifically.\n\nIt took two hours to shift the rocks. She stood, tested her weight, looked at him with those sky-colored eyes. Then she turned and walked up the glacier without looking back.\n\nThe gift came three days later, when Karma woke to find he could hear the mountain breathing." },
      { title: "The River That Remembers", description: "A village elder tells of a river that holds the memories of all who have crossed it — and what happens when someone asks it to forget.", duration: 1780, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", episodeNumber: 2, isLocked: false, playCount: 10200, transcript: "" },
      { title: "The Weaver of Clouds", description: "High above the treeline lives a woman who weaves the clouds each morning. When her loom breaks, everything below begins to dry.", duration: 1540, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", episodeNumber: 3, isLocked: false, playCount: 8100, transcript: "" },
      { title: "Two Brothers and the Oracle", description: "Twin brothers receive the same prophecy from an oracle, and spend their lives fulfilling it in opposite ways.", duration: 1920, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", episodeNumber: 4, isLocked: true, playCount: 6200, transcript: "" },
    ]
  },
  {
    title: "Dark Web",
    description: "A journalist investigating online extremism starts receiving direct messages from an anonymous source who seems to know exactly what she is about to discover — before she discovers it.",
    coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600",
    genre: "Cyber Thriller",
    language: "English",
    narrator: "Sam Rivers",
    rating: 4.4,
    isFeatured: false,
    isTrending: true,
    totalPlays: 67800,
    tags: ["cyber", "thriller", "journalism", "dark web", "hacking"],
    episodes: [
      { title: "The Source", description: "Investigative journalist Jo Park receives an encrypted message that dismantles her entire theory about her current story.", duration: 2030, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3", episodeNumber: 1, isLocked: false, playCount: 24600, transcript: "I have been a journalist for eleven years. I have had good sources and bad sources, reliable sources and sources who led me directly into the worst professional disasters of my career. I have learned to be careful.\n\nI was not careful enough for this.\n\nThe message came through a platform I hadn't used in years — an old encrypted messaging app, barely maintained, the kind that serious operational security people had moved away from. I still had the app because inertia is a powerful force in digital life.\n\nThe message said: 'Your current story about the Forum is wrong. Not factually wrong — directionally wrong. You are following the trail they want you to follow. Stop. Meet me in the comments of the 2019 Meridian article on your site. Post a comment at 3 PM on Friday. I will respond. Don't use your real name.'\n\nThe Forum was a network I had been investigating for four months. The message knew that. The message knew details about my investigation that I hadn't published and hadn't told anyone.\n\nI went back and re-examined everything I thought I knew." },
      { title: "Mirror Sites", description: "Jo discovers the Forum has been running a sophisticated mirror operation, feeding false information to multiple journalists simultaneously.", duration: 2180, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3", episodeNumber: 2, isLocked: false, playCount: 19300, transcript: "" },
      { title: "The Real Network", description: "The anonymous source reveals they are a former insider — and the Forum's actual goal is far more mundane and far more dangerous than anyone suspected.", duration: 2360, audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", episodeNumber: 3, isLocked: true, playCount: 13200, transcript: "" },
    ]
  }
];

export const sampleProducts = [
  // Accessories
  { name: "Naad Wireless Earbuds Pro", description: "Premium audiophile-grade wireless earbuds with 40-hour battery life, active noise cancellation, and a custom tuning profile optimized for spoken word and voice audio. The warmth driver ensures narrators sound exactly as intended.", price: 4999, images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600"], category: "accessories", tags: ["earbuds", "wireless", "premium", "audio"], stock: 150, rating: 4.8, reviews: 234 },
  { name: "Story Notebook — Leather Bound", description: "Handmade full-grain leather journal with 200 pages of archival-quality paper, a ribbon bookmark, and a custom debossed logo. Perfect for jotting notes during your listening sessions.", price: 899, images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600"], category: "accessories", tags: ["notebook", "leather", "writing", "journal"], stock: 80, rating: 4.6, reviews: 89 },
  { name: "Himalayan Crystal Bookmark Set", description: "Set of 3 hand-cut crystal bookmarks with brass fittings, each inscribed with a quote from Folktales from the Himalayas. A tactile reminder of the story world.", price: 349, images: ["https://images.unsplash.com/photo-1481237560839-5a9e7c7ff00e?w=600"], category: "accessories", relatedSeries: "Folktales from the Himalayas", tags: ["bookmark", "crystal", "himalayan", "gift"], stock: 200, rating: 4.4, reviews: 56 },
  { name: "Naad Podcast Mic Stand — Walnut", description: "Desktop microphone stand crafted from solid walnut with adjustable height and a minimalist aesthetic that fits any workspace. For creators who want quality audio and beautiful design.", price: 2199, images: ["https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=600"], category: "accessories", tags: ["mic", "stand", "walnut", "creator"], stock: 45, rating: 4.7, reviews: 78 },
  
  // Clothing
  { name: "The Listener Oversized Tee — Midnight", description: "Premium 320gsm cotton oversized tee with a minimal embroidered waveform motif on the chest. Pre-washed for a lived-in feel. Sizes XS–3XL.", price: 799, images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600"], category: "clothing", tags: ["tshirt", "cotton", "oversized", "minimal"], stock: 300, rating: 4.5, reviews: 145 },
  { name: "Silk Road Scarf — Hand Block Printed", description: "100% silk scarf hand block-printed in Jaipur with a pattern inspired by the trade routes of The Silk Road Chronicles. Each piece is slightly unique. 180cm × 80cm.", price: 1499, images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600"], category: "clothing", relatedSeries: "The Silk Road Chronicles", tags: ["scarf", "silk", "handmade", "printed"], stock: 60, rating: 4.9, reviews: 42 },
  { name: "Monsoon Linen Kurta — Unisex", description: "Breezy handloom linen kurta with subtle rain-drop embroidery along the yoke and cuffs, inspired by Mumbai Monsoon. Breathable, sustainable, beautiful.", price: 1899, images: ["https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600"], category: "clothing", relatedSeries: "Mumbai Monsoon", tags: ["kurta", "linen", "monsoon", "sustainable"], stock: 120, rating: 4.6, reviews: 67 },
  { name: "Dark Web Hoodie — Charcoal", description: "Heavyweight 420gsm French terry hoodie in washed charcoal with a glitch-text back print. Drop-shoulder fit. Double-lined hood. Feels like a safe house.", price: 2499, images: ["https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600"], category: "clothing", relatedSeries: "Dark Web", tags: ["hoodie", "streetwear", "cyber", "heavy"], stock: 90, rating: 4.7, reviews: 98 },
  
  // Handicrafts
  { name: "Himalayan Singing Bowl — Large", description: "Hand-hammered bronze singing bowl from Kathmandu, approximately 22cm diameter. Comes with a wooden striker and silk cushion. The resonance clears the mind for deep listening.", price: 2799, images: ["https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?w=600"], category: "handicrafts", relatedSeries: "Folktales from the Himalayas", tags: ["bowl", "himalayan", "meditation", "bronze"], stock: 30, rating: 4.9, reviews: 112 },
  { name: "Caravanserai Miniature — Painted Terracotta", description: "Hand-painted terracotta miniature depicting a Silk Road caravanserai at dusk, crafted by artisans in Rajasthan. Each piece is one of a kind. Approx 12cm × 8cm.", price: 1299, images: ["https://images.unsplash.com/photo-1515023115689-589c33041d3c?w=600"], category: "handicrafts", relatedSeries: "The Silk Road Chronicles", tags: ["miniature", "terracotta", "handpainted", "collectible"], stock: 25, rating: 4.8, reviews: 34 },
  { name: "Woven Wall Tapestry — Mountain Spirit", description: "Hand-loomed wool tapestry in natural dyes depicting a snow leopard against a mountain backdrop. 60cm × 90cm. Made by a women's cooperative in Himachal Pradesh.", price: 3499, images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], category: "handicrafts", tags: ["tapestry", "wool", "handloom", "wall art", "himalayan"], stock: 15, rating: 4.9, reviews: 28 },
  { name: "Mumbai Street Art Print — Monsoon Series", description: "Set of 3 archival giclee prints (30cm × 40cm each) by Mumbai street artist Priya Joshi, capturing the city across three monsoon seasons. Numbered edition of 200.", price: 1999, images: ["https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600"], category: "handicrafts", relatedSeries: "Mumbai Monsoon", tags: ["print", "art", "mumbai", "monsoon", "limited edition"], stock: 50, rating: 4.7, reviews: 45 },
  
  // Merchandise
  { name: "Naad Premium Tote — Natural Canvas", description: "Heavy-duty 16oz canvas tote with leather handles and an internal pocket. Screenprinted with the Naad waveform logo. Carries a good book, your headphones, and the afternoon.", price: 599, images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600"], category: "merchandise", tags: ["tote", "canvas", "bag", "eco"], stock: 400, rating: 4.4, reviews: 189 },
  { name: "Enamel Pin Set — Series Characters", description: "Set of 6 hand-illustrated enamel pins featuring characters and symbols from Naad's most popular series. Soft enamel, gold backing, butterfly clasps. 3cm each.", price: 449, images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"], category: "merchandise", tags: ["pins", "enamel", "collectible", "characters"], stock: 500, rating: 4.6, reviews: 234 },
  { name: "The Quantum Diaries — Collector's Box", description: "Deluxe collector's edition box for The Quantum Diaries including a printed transcript book, a quantum mechanics primer, a replica 'message from the future' prop, and a limited print.", price: 2999, images: ["https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600"], category: "merchandise", relatedSeries: "The Quantum Diaries", tags: ["collectible", "box set", "limited edition", "quantum"], stock: 100, rating: 4.9, reviews: 67 },
];
